<?php

$annonces = [
    [
        'id'          => 1,
        'type'        => 'alternance',
        'titre'       => 'Développeur Web Full Stack',
        'entreprise'  => 'Tech Innovation',
        'lieu'        => 'Paris, Île-de-France',
        'duree'       => '24 mois',
        'vues'        => 412,
        'salaire'     => '13 - 14€ / heure',
        'niveau'      => 'Bac +3',
        'secteur'     => 'Développement web',
        'description' => 'Rejoignez notre équipe pour développer des applications web modernes en React et Symfony. Vous travaillerez sur des projets clients variés dans un environnement agile.',
        'tags'        => ['Paris', 'Alternance', 'Bac +3', '13 - 14€ / heure', 'Exp. 0 à 1 an'],
    ],
    [
        'id'          => 2,
        'type'        => 'alternance',
        'titre'       => 'Ingénieur Cybersécurité',
        'entreprise'  => 'SecureNet',
        'lieu'        => 'Lyon, Auvergne-Rhône-Alpes',
        'duree'       => '12 mois',
        'vues'        => 289,
        'salaire'     => '15 - 17€ / heure',
        'niveau'      => 'Bac +5',
        'secteur'     => 'Cybersécurité',
        'description' => 'Participez à l\'audit et à la sécurisation des infrastructures réseau de nos clients grands comptes. Vous serez formé aux outils SIEM et aux techniques de pentest.',
        'tags'        => ['Lyon', 'Alternance', 'Bac +5', '15 - 17€ / heure', 'Exp. 1 à 3 ans'],
    ],
    [
        'id'          => 3,
        'type'        => 'stage',
        'titre'       => 'Data Analyst',
        'entreprise'  => 'DataCorp',
        'lieu'        => 'Bordeaux, Nouvelle-Aquitaine',
        'duree'       => '6 mois',
        'vues'        => 731,
        'salaire'     => '600€ / mois',
        'niveau'      => 'Bac +4',
        'secteur'     => 'Data / IA',
        'description' => 'Au sein de l\'équipe Data, vous analyserez des volumes importants de données clients pour produire des rapports et tableaux de bord sous Power BI.',
        'tags'        => ['Bordeaux', 'Stage', 'Bac +4', '600€ / mois', 'Exp. 0 à 1 an'],
    ],
    [
        'id'          => 4,
        'type'        => 'alternance',
        'titre'       => 'Administrateur Réseaux',
        'entreprise'  => 'NetSystems',
        'lieu'        => 'Toulouse, Occitanie',
        'duree'       => '24 mois',
        'vues'        => 178,
        'salaire'     => '14 - 15€ / heure',
        'niveau'      => 'Bac +2',
        'secteur'     => 'Réseau & Systèmes',
        'description' => 'Vous administrerez les infrastructures réseau (switches, routeurs Cisco) et participerez aux projets de migration vers le cloud de notre parc informatique.',
        'tags'        => ['Toulouse', 'Alternance', 'Bac +2', '14 - 15€ / heure', 'Exp. 0 à 1 an'],
    ],
    [
        'id'          => 5,
        'type'        => 'stage',
        'titre'       => 'Développeur Mobile iOS',
        'entreprise'  => 'AppStudio',
        'lieu'        => 'Paris, Île-de-France',
        'duree'       => '6 mois',
        'vues'        => 543,
        'salaire'     => '650€ / mois',
        'niveau'      => 'Bac +4',
        'secteur'     => 'Développement web',
        'description' => 'Intégrez notre studio mobile pour développer de nouvelles fonctionnalités sur notre application iOS (Swift/SwiftUI). Vous travaillerez en étroite collaboration avec les designers UX.',
        'tags'        => ['Paris', 'Stage', 'Bac +4', '650€ / mois', 'Exp. 0 à 1 an'],
    ],
    [
        'id'          => 6,
        'type'        => 'alternance',
        'titre'       => 'Ingénieur DevOps',
        'entreprise'  => 'CloudFactory',
        'lieu'        => 'Nantes, Pays de la Loire',
        'duree'       => '12 mois',
        'vues'        => 367,
        'salaire'     => '16 - 18€ / heure',
        'niveau'      => 'Bac +5',
        'secteur'     => 'Réseau & Systèmes',
        'description' => 'Vous automatiserez les pipelines CI/CD et gérerez les environnements Kubernetes en production. Une appétence pour Docker et Terraform est souhaitée.',
        'tags'        => ['Nantes', 'Alternance', 'Bac +5', '16 - 18€ / heure', 'Exp. 1 à 3 ans'],
    ],
    [
        'id'          => 7,
        'type'        => 'stage',
        'titre'       => 'UX/UI Designer',
        'entreprise'  => 'DesignHub',
        'lieu'        => 'Lille, Hauts-de-France',
        'duree'       => '4 mois',
        'vues'        => 892,
        'salaire'     => '550€ / mois',
        'niveau'      => 'Bac +3',
        'secteur'     => 'Marketing digital',
        'description' => 'Concevez des interfaces intuitives pour nos clients e-commerce. Vous réaliserez des wireframes et prototypes sur Figma, et conduirez des tests utilisateurs.',
        'tags'        => ['Lille', 'Stage', 'Bac +3', '550€ / mois', 'Exp. 0 à 1 an'],
    ],
    [
        'id'          => 8,
        'type'        => 'alternance',
        'titre'       => 'Développeur Backend PHP',
        'entreprise'  => 'WebAgency',
        'lieu'        => 'Strasbourg, Grand Est',
        'duree'       => '24 mois',
        'vues'        => 214,
        'salaire'     => '13 - 15€ / heure',
        'niveau'      => 'Bac +3',
        'secteur'     => 'Développement web',
        'description' => 'Rejoignez notre agence web pour développer et maintenir des applications PHP/Laravel. Vous interviendrez sur des projets clients allant des sites vitrines aux plateformes SaaS.',
        'tags'        => ['Strasbourg', 'Alternance', 'Bac +3', '13 - 15€ / heure', 'Exp. 0 à 1 an'],
    ],
    [
        'id'          => 9,
        'type'        => 'stage',
        'titre'       => 'Chargé de Marketing Digital',
        'entreprise'  => 'GrowthLab',
        'lieu'        => 'Lyon, Auvergne-Rhône-Alpes',
        'duree'       => '6 mois',
        'vues'        => 654,
        'salaire'     => '600€ / mois',
        'niveau'      => 'Bac +4',
        'secteur'     => 'Marketing digital',
        'description' => 'Pilotez les campagnes SEA/SEO et réseaux sociaux de nos marques partenaires. Vous analyserez les performances via Google Analytics et proposerez des optimisations.',
        'tags'        => ['Lyon', 'Stage', 'Bac +4', '600€ / mois', 'Exp. 0 à 1 an'],
    ],
    [
        'id'          => 10,
        'type'        => 'alternance',
        'titre'       => 'Technicien Support Informatique',
        'entreprise'  => 'HelpDesk Pro',
        'lieu'        => 'Marseille, Provence-Alpes-Côte d\'Azur',
        'duree'       => '12 mois',
        'vues'        => 301,
        'salaire'     => '12 - 13€ / heure',
        'niveau'      => 'Bac +2',
        'secteur'     => 'Réseau & Systèmes',
        'description' => 'Assurez le support N1/N2 pour les utilisateurs d\'un grand groupe (Active Directory, Office 365). Vous participerez également aux déploiements de postes de travail.',
        'tags'        => ['Marseille', 'Alternance', 'Bac +2', '12 - 13€ / heure', 'Exp. 0 à 1 an'],
    ],
];