<?php
$entreprises = [
    [
        'id'             => 1,
        'Logo'           => '',
        'Nom_entreprise' => 'Dassault Systèmes',
        'Secteur'        => 'Logiciels 3D',
        'Rating'         => 4.2,
        'Nombre_avis'    => 1250,
        'Nombre_offres'  => 45,
        'Description'    => 'Dassault Systèmes est un éditeur français de logiciels de conception 3D, simulation et gestion du cycle de vie des produits. Présent dans plus de 140 pays, le groupe accompagne industriels et entreprises dans leur transformation numérique grâce à sa plateforme 3DEXPERIENCE.',
    ],
    [
        'id'             => 2,
        'Logo'           => '',
        'Nom_entreprise' => 'Capgemini',
        'Secteur'        => 'Services IT',
        'Rating'         => 4.0,
        'Nombre_avis'    => 3200,
        'Nombre_offres'  => 120,
        'Description'    => 'Capgemini est un leader mondial du conseil, des services informatiques et de la transformation digitale. Fort de plus de 350 000 collaborateurs dans le monde, le groupe accompagne ses clients dans leurs projets cloud, data, cybersécurité et développement logiciel.',
    ],
    [
        'id'             => 3,
        'Logo'           => '',
        'Nom_entreprise' => 'Sopra Steria',
        'Secteur'        => 'Conseil IT',
        'Rating'         => 3.9,
        'Nombre_avis'    => 1800,
        'Nombre_offres'  => 85,
        'Description'    => 'Sopra Steria est un groupe européen de conseil, de services numériques et d\'édition de logiciels. Il accompagne ses clients dans leur transformation digitale en combinant expertise sectorielle et maîtrise des technologies les plus récentes.',
    ],
    [
        'id'             => 4,
        'Logo'           => '',
        'Nom_entreprise' => 'Alten',
        'Secteur'        => 'Ingénierie',
        'Rating'         => 3.8,
        'Nombre_avis'    => 2100,
        'Nombre_offres'  => 95,
        'Description'    => 'Alten est un groupe international de conseil en ingénierie et technologie. Il intervient sur des projets R&D et informatiques pour de grands comptes dans les secteurs de l\'aéronautique, de l\'automobile, de l\'énergie et des télécommunications.',
    ],
    [
        'id'             => 5,
        'Logo'           => '',
        'Nom_entreprise' => 'Atos',
        'Secteur'        => 'Services Numériques',
        'Rating'         => 3.5,
        'Nombre_avis'    => 4500,
        'Nombre_offres'  => 200,
        'Description'    => 'Atos est un leader international de la transformation digitale. Il propose des solutions de cloud hybride, de cybersécurité et de calcul haute performance pour accompagner les entreprises et les gouvernements dans leur transition numérique.',
    ],
    [
        'id'             => 6,
        'Logo'           => '',
        'Nom_entreprise' => 'Orange',
        'Secteur'        => 'Télécoms',
        'Rating'         => 4.1,
        'Nombre_avis'    => 3800,
        'Nombre_offres'  => 150,
        'Description'    => 'Orange est l\'un des principaux opérateurs de télécommunications mondiaux. Il offre des services mobile, internet fixe, TV et cloud à des millions de clients en France et à l\'international, tout en investissant massivement dans la 5G et la fibre optique.',
    ],
    [
        'id'             => 7,
        'Logo'           => '',
        'Nom_entreprise' => 'Alcatel-Lucent Enterprise',
        'Secteur'        => 'Réseaux',
        'Rating'         => 3.7,
        'Nombre_avis'    => 900,
        'Nombre_offres'  => 35,
        'Description'    => 'Alcatel-Lucent Enterprise conçoit des solutions de réseaux, de communications et de cloud pour les entreprises. Ses produits couvrent les infrastructures réseau, la téléphonie d\'entreprise et les solutions de collaboration à destination des secteurs public et privé.',
    ],
    [
        'id'             => 8,
        'Logo'           => '',
        'Nom_entreprise' => 'Thales',
        'Secteur'        => 'Défense & Sécurité',
        'Rating'         => 4.0,
        'Nombre_avis'    => 2200,
        'Nombre_offres'  => 110,
        'Description'    => 'Thales est un groupe technologique mondial opérant dans les domaines de la défense, de l\'aérospatial, du transport et de la cybersécurité. Il développe des systèmes critiques pour les armées, les gouvernements et les opérateurs d\'infrastructures essentielles.',
    ],
    [
        'id'             => 9,
        'Logo'           => '',
        'Nom_entreprise' => 'OVHcloud',
        'Secteur'        => 'Cloud Computing',
        'Rating'         => 3.9,
        'Nombre_avis'    => 1400,
        'Nombre_offres'  => 60,
        'Description'    => 'OVHcloud est le premier hébergeur européen et l\'un des leaders mondiaux du cloud. Il propose des solutions d\'infrastructure (serveurs dédiés, VPS, cloud public et privé) souveraines et compétitives, avec des datacenters répartis sur quatre continents.',
    ],
    [
        'id'             => 10,
        'Logo'           => '',
        'Nom_entreprise' => 'Criteo',
        'Secteur'        => 'Publicité en Ligne',
        'Rating'         => 4.3,
        'Nombre_avis'    => 1100,
        'Nombre_offres'  => 50,
        'Description'    => 'Criteo est une entreprise technologique spécialisée dans la publicité digitale et le marketing à la performance. Sa plateforme utilise l\'intelligence artificielle pour diffuser des publicités personnalisées et mesurer leur impact pour des milliers d\'annonceurs dans le monde.',
    ],
    [
        'id'             => 11,
        'Logo'           => '',
        'Nom_entreprise' => 'Worldline',
        'Secteur'        => 'Paiements',
        'Rating'         => 3.6,
        'Nombre_avis'    => 1600,
        'Nombre_offres'  => 75,
        'Description'    => 'Worldline est un leader européen des services de paiement et de transaction. Il accompagne banques, commerçants et administrations dans la gestion de leurs flux financiers grâce à des solutions sécurisées de paiement en ligne, en point de vente et mobile.',
    ],
    [
        'id'             => 12,
        'Logo'           => '',
        'Nom_entreprise' => 'Lectra',
        'Secteur'        => 'Logiciels Industriels',
        'Rating'         => 3.8,
        'Nombre_avis'    => 750,
        'Nombre_offres'  => 30,
        'Description'    => 'Lectra est un éditeur de logiciels et fabricant de machines de découpe automatisée pour les industries de la mode, de l\'automobile et de l\'ameublement. Ses solutions intègrent intelligence artificielle et IoT pour optimiser les processus de production.',
    ],
    [
        'id'             => 13,
        'Logo'           => '',
        'Nom_entreprise' => 'STMicroelectronics',
        'Secteur'        => 'Semi-conducteurs',
        'Rating'         => 4.1,
        'Nombre_avis'    => 2900,
        'Nombre_offres'  => 130,
        'Description'    => 'STMicroelectronics est un groupe franco-italien leader mondial dans la conception et la fabrication de semi-conducteurs. Ses composants équipent des milliards d\'appareils électroniques dans les domaines de l\'automobile, de l\'industrie, de l\'IoT et du grand public.',
    ],
    [
        'id'             => 14,
        'Logo'           => '',
        'Nom_entreprise' => 'Schneider Electric',
        'Secteur'        => 'Automatisation',
        'Rating'         => 4.2,
        'Nombre_avis'    => 3500,
        'Nombre_offres'  => 140,
        'Description'    => 'Schneider Electric est un spécialiste mondial de la gestion de l\'énergie et de l\'automatisation industrielle. Il propose des solutions pour optimiser la consommation énergétique des bâtiments, des datacenters et des infrastructures industrielles à travers le monde.',
    ],
    [
        'id'             => 15,
        'Logo'           => '',
        'Nom_entreprise' => 'Renault Digital',
        'Secteur'        => 'Mobilité Connectée',
        'Rating'         => 3.9,
        'Nombre_avis'    => 1900,
        'Nombre_offres'  => 80,
        'Description'    => 'Renault Digital est la filiale tech du groupe Renault, dédiée au développement de solutions numériques pour la mobilité connectée. Elle pilote les projets d\'applications mobiles, de véhicules connectés et de transformation digitale interne du groupe.',
    ],
    [
        'id'             => 16,
        'Logo'           => '',
        'Nom_entreprise' => 'Devoteam',
        'Secteur'        => 'Transformation Digitale',
        'Rating'         => 4.0,
        'Nombre_avis'    => 1300,
        'Nombre_offres'  => 55,
        'Description'    => 'Devoteam est un cabinet de conseil spécialisé dans la transformation digitale des entreprises. Il accompagne ses clients sur les sujets cloud (Google, AWS, Azure), cybersécurité, data et agilité organisationnelle à travers une présence dans plus de 20 pays.',
    ],
    [
        'id'             => 17,
        'Logo'           => '',
        'Nom_entreprise' => 'Ubisoft',
        'Secteur'        => 'Jeux Vidéo',
        'Rating'         => 3.7,
        'Nombre_avis'    => 2500,
        'Nombre_offres'  => 90,
        'Description'    => 'Ubisoft est l\'un des plus grands studios de développement et d\'édition de jeux vidéo au monde. Créateur de franchises emblématiques comme Assassin\'s Creed et Far Cry, il réunit plus de 20 000 développeurs et artistes dans ses studios répartis sur les cinq continents.',
    ],
    [
        'id'             => 18,
        'Logo'           => '',
        'Nom_entreprise' => 'Dataiku',
        'Secteur'        => 'Data Science',
        'Rating'         => 4.4,
        'Nombre_avis'    => 850,
        'Nombre_offres'  => 40,
        'Description'    => 'Dataiku est une entreprise française spécialisée dans les plateformes de data science et d\'intelligence artificielle. Sa solution Everyday AI permet aux équipes data et métiers de collaborer pour concevoir, déployer et monitorer des modèles d\'IA à grande échelle.',
    ],
    [
        'id'             => 19,
        'Logo'           => '',
        'Nom_entreprise' => 'Doctolib',
        'Secteur'        => 'Santé Digitale',
        'Rating'         => 4.3,
        'Nombre_avis'    => 1600,
        'Nombre_offres'  => 70,
        'Description'    => 'Doctolib est la première plateforme européenne de santé digitale. Elle simplifie la prise de rendez-vous médicaux pour les patients et la gestion des agendas pour les professionnels de santé, avec plus de 80 millions d\'utilisateurs en France, Allemagne et Italie.',
    ],
    [
        'id'             => 20,
        'Logo'           => '',
        'Nom_entreprise' => 'BlaBlaCar',
        'Secteur'        => 'Covoiturage',
        'Rating'         => 4.1,
        'Nombre_avis'    => 1200,
        'Nombre_offres'  => 45,
        'Description'    => 'BlaBlaCar est la plateforme mondiale de covoiturage longue distance et de transport en commun. Présente dans plus de 20 pays, elle met en relation conducteurs et passagers pour des trajets économiques et écologiques, avec plus de 100 millions de membres inscrits.',
    ],
];
?>